### ISSUE TITLE
Test failure in master (httparty/patch_spec.rb) with httparty 0.18.1

### ISSUE THREAD

**Issue by sbleon** [ECHOInternational/your_membership#10]
I'm getting a test failure in master when using httparty 0.18.1. See attached test output. The test suite is green with httparty 0.16.4.
[test_output.txt](https://github.com/ECHOInternational/your_membership/files/5997129/test_output.txt)

**Comment by jaredbeck** [comment]
Fixed by https://github.com/ECHOInternational/your_membership/pull/11 .  You're going to like it, I think :smile:
