### ISSUE TITLE
Need access to gem on rubygems and admin access on GitHub

### ISSUE THREAD

**Issue by sbleon** [ECHOInternational/your_membership#5]
Hi, @npflood! Can you add me and a couple of my colleagues as
authors http://guides.rubygems.org/command-reference/#gem-owner on
rubygems.org? Our emails are:

leon@singlebrook.com
codingcyborg@gmail.com
jared@jaredbeck.com

Once that’s done I can make a new release of the gem :-)

One more request: Please either make me an admin on these repos and/or give @rodel30 and @jaredbeck write access. Thanks!

**Comment by npflood** [comment]
I've made you an admin. Sorry this took so long, I've been away and missed your messages.

**Comment by sbleon** [comment]
Thanks, @npflood! Can you also make me an admin and gem owner on
`omniauth-your-membership-token`?

**Comment by sbleon** [comment]
Oh, and we still need gem ownership on rubygems.org, please!

**Comment by npflood** [comment]
Done and Done. Let me know if I missed anything.

**Comment by sbleon** [comment]
Looks good. Thanks, Nathan!
